import Head from 'next/head'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      rghjkl
      <i className="fa-solid fa-basketball text-3xl"></i>
    </div>
  )
}
