import { useState } from "react";
import Head from "next/head";
import { FunTip } from "../../components/FunTip";
import { Search } from "../../components/Search";
import Link from "next/link";

const Creations = () => {
 const [searchVal, setSearchVal] = useState("");
 return (
  <div className="w-full flex">
   <Head>
    <title>Creations</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <div className="flex-1 min-h-screen bg-slate-50 dark:bg-slate-800 p-10">
    <h1 className="text-4xl mb-7 dark:text-slate-50">Creations</h1>
    <Search searchVal={searchVal} setSearchVal={setSearchVal} />
   </div>
   <div className="w-[25%] bg-slate-100 dark:bg-slate-900 min-h-screen p-10 flex flex-col items-center">
    <Link className="w-full" href={`/creations/new`}>
     <div className="text-center py-4 text-2xl mb-10 rounded-xl bg-gradient-to-r dark:text-slate-900 text-slate-50 from-cyan-500 to-blue-600 hover:scale-110 cursor-pointer ease-in-out duration-500">
      <i className={`fa-solid fa-plus mr-3`}></i>
      New theme
     </div>
    </Link>
    <FunTip
     tipText={
      "These all themes are created by our community. Make sure you don't repeate somebody's theme before creating and you don't insult anyone."
     }
    ></FunTip>
   </div>
  </div>
 );
};

export default Creations;
