import Head from "next/head";


export const getServerSideProps = async (context) => {
 const { id } = context.params;
 const res = await fetch(`${process.env.API_HOST}/me`, {
  method: "POST",
  headers: {
   "Content-Type": "application/json;charset=utf-8",
  },
  body: JSON.stringify({_id: id.toString()}),
 });
 const data = await res.json();
 return {
  props: { data: data },
 };
};

const Me = ({ data }) => {

 return (
  <div className="w-full flex">
   <Head>
    <title>{data.login}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <div className="flex-1 h-screen bg-slate-50 dark:bg-slate-800 p-10">

   </div>
   <div className="w-[25%] bg-slate-100 dark:bg-slate-900 min-h-screen">
    <div className="flex flex-col items-start px-10 pt-10">
     <h1 className="text-2xl text-slate-500 mb-3 self-center">
      Popular themes here:
     </h1>
    </div>
   </div>
  </div>
 );
};

export default Me;
