import { useState } from "react";
import Head from "next/head";
import { Search } from "../../components/Search";
import { FunTip } from "../../components/FunTip";
import { Theme } from "../../components/Theme/Theme";
import { useRouter } from "next/router";
import Link from "next/link";

export const getServerSideProps = async (context) => {
 const { category } = context.params;
 const res = await fetch(`http://localhost:4444/categories/${category}`);
 const data = await res.json();
 if (!data) {
  return {
   notFound: true,
  };
 }
 return {
  props: { themes: data },
 };
};

const Category = ({ themes }) => {
 const [searchVal, setSearchVal] = useState("");

 const router = useRouter();
 const { category } = router.query;

 const CountStars = (arr) => {
  let sum = 0;
  arr.map((item) => (sum += item.stars));
  return sum / arr.length;
 };

 return (
  <div className="w-full flex">
   <Head>
    <title>{category.charAt(0).toUpperCase() + category.slice(1)}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <div className="flex-1 h-screen bg-slate-50 dark:bg-slate-800 p-10">
    <Link href={`/`}>
     <div className="inline-flex items-center mb-3 text-2xl text-slate-500 cursor-pointer hover:scale-110 ease-in-out duration-300">
      <i class="fa-solid fa-chevron-left mr-2"></i>
      <h1>Caregories</h1>
     </div>
    </Link>
    <h1 className="text-4xl mb-7 dark:text-slate-50 capitalize">{category}</h1>
    <Search searchVal={searchVal} setSearchVal={setSearchVal} />

    <div className="grid gap-4 grid-cols-2">
     {themes.map(
      (theme) =>
       theme.name.slice(0, searchVal.length).toUpperCase() ===
        searchVal.toUpperCase() && (
        <Theme
         name={theme.name}
         stars={CountStars(theme.stars)}
         imgUrl={theme.imgUrl}
         author={theme.author}
         description={theme.description}
        />
       )
     )}
    </div>
   </div>
   <div className="w-[25%] bg-slate-100 dark:bg-slate-900 min-h-screen">
    <div className="flex flex-col items-start px-10 pt-10">
     <FunTip
      tipText={
       "These are categories with topics created by our 1 of 2 team, but if there is no topic that you are interested in, you can find much more in our community creations or create a topic by yourself in the same section."
      }
     ></FunTip>
     <h1 className="text-2xl text-slate-500 mb-3 self-center">
      Popular themes here:
     </h1>
    </div>
   </div>
  </div>
 );
};

export default Category;
